#!/usr/bin/python3

from sys import argv

text_file = open(argv[1], "r")
lst = text_file.read().splitlines()

for el in lst:
    elem = int(el)
    for i in range(2, elem):
        if elem % i == 0:
            for j in range(int(elem / 2), 1, -1):
                if elem % j == 0 and i * j  == elem:
                    print("{}={}*{}".format(elem, j, i))
                    break
            break

        
